export const SKILLS = {
  'Languages': [
    { id: 'javascript', label: 'JavaScript', color: 'F7DF1E', logoColor: 'black' },
    { id: 'typescript', label: 'TypeScript', color: '007ACC' },
    { id: 'python', label: 'Python', color: '3670A0' },
    { id: 'java', label: 'Java', color: 'ED8B00', logo: 'openjdk' },
    { id: 'c', label: 'C', color: '00599C' },
    { id: 'cpp', label: 'C++', color: '00599C', logo: 'cplusplus' },
    { id: 'csharp', label: 'C#', color: '239120', logo: 'csharp' },
    { id: 'go', label: 'Go', color: '00ADD8' },
    { id: 'rust', label: 'Rust', color: 'CE422B' },
    { id: 'php', label: 'PHP', color: '777BB4' },
    { id: 'ruby', label: 'Ruby', color: 'CC342D' },
    { id: 'swift', label: 'Swift', color: 'FA7343' },
    { id: 'kotlin', label: 'Kotlin', color: '7F52FF' },
    { id: 'dart', label: 'Dart', color: '0175C2' },
    { id: 'r', label: 'R', color: '276DC3' },
    { id: 'scala', label: 'Scala', color: 'DC322F' },
    { id: 'elixir', label: 'Elixir', color: '4B275F' },
    { id: 'haskell', label: 'Haskell', color: '5D4F85' },
    { id: 'lua', label: 'Lua', color: '2C2D72' },
    { id: 'perl', label: 'Perl', color: '39457E' },
    { id: 'html5', label: 'HTML5', color: 'E34F26', logo: 'html5' },
    { id: 'css3', label: 'CSS3', color: '1572B6', logo: 'css3' },
    { id: 'bash', label: 'Bash', color: '4EAA25', logo: 'gnubash' },
    { id: 'solidity', label: 'Solidity', color: '363636' },
  ],
  'Frontend': [
    { id: 'react', label: 'React', color: '20232A', logoColor: '61DAFB' },
    { id: 'nextjs', label: 'Next.js', color: '000000', logo: 'nextdotjs' },
    { id: 'vue', label: 'Vue.js', color: '35495E', logo: 'vuedotjs', logoColor: '4FC08D' },
    { id: 'nuxt', label: 'Nuxt.js', color: '002E3B', logo: 'nuxtdotjs', logoColor: '00DC82' },
    { id: 'angular', label: 'Angular', color: 'DD0031' },
    { id: 'svelte', label: 'Svelte', color: 'FF3E00' },
    { id: 'remix', label: 'Remix', color: '000000', logo: 'remix' },
    { id: 'astro', label: 'Astro', color: 'BC52EE', logo: 'astro' },
    { id: 'tailwind', label: 'Tailwind CSS', color: '06B6D4', logo: 'tailwindcss' },
    { id: 'bootstrap', label: 'Bootstrap', color: '7952B3' },
    { id: 'materialui', label: 'Material UI', color: '007FFF', logo: 'mui' },
    { id: 'sass', label: 'Sass', color: 'CC6699' },
    { id: 'redux', label: 'Redux', color: '764ABC' },
    { id: 'graphql', label: 'GraphQL', color: 'E10098' },
    { id: 'vite', label: 'Vite', color: '646CFF' },
    { id: 'webpack', label: 'Webpack', color: '8DD6F9', logoColor: 'black' },
    { id: 'jquery', label: 'jQuery', color: '0769AD' },
  ],
  'Backend': [
    { id: 'nodejs', label: 'Node.js', color: '6DA55F', logo: 'nodedotjs' },
    { id: 'express', label: 'Express.js', color: '404D59', logo: 'express' },
    { id: 'nestjs', label: 'NestJS', color: 'E0234E' },
    { id: 'fastapi', label: 'FastAPI', color: '005571' },
    { id: 'django', label: 'Django', color: '092E20' },
    { id: 'flask', label: 'Flask', color: '000000' },
    { id: 'spring', label: 'Spring', color: '6DB33F' },
    { id: 'laravel', label: 'Laravel', color: 'FF2D20' },
    { id: 'rails', label: 'Rails', color: 'CC0000', logo: 'rubyonrails' },
    { id: 'deno', label: 'Deno', color: '000000' },
    { id: 'bun', label: 'Bun', color: 'FBF0DF', logoColor: 'black' },
    { id: 'hono', label: 'Hono', color: 'E36002' },
    { id: 'trpc', label: 'tRPC', color: '2596BE' },
  ],
  'Mobile': [
    { id: 'reactnative', label: 'React Native', color: '20232A', logo: 'react', logoColor: '61DAFB' },
    { id: 'flutter', label: 'Flutter', color: '02569B' },
    { id: 'android', label: 'Android', color: '3DDC84', logoColor: 'white' },
    { id: 'swift-mobile', label: 'iOS / Swift', color: 'FA7343', logo: 'swift' },
    { id: 'expo', label: 'Expo', color: '000020' },
    { id: 'ionic', label: 'Ionic', color: '3880FF' },
    { id: 'xamarin', label: 'Xamarin', color: '3199DC' },
  ],
  'Database': [
    { id: 'mysql', label: 'MySQL', color: '4479A1', logoColor: 'white' },
    { id: 'postgresql', label: 'PostgreSQL', color: '316192' },
    { id: 'mongodb', label: 'MongoDB', color: '47A248' },
    { id: 'redis', label: 'Redis', color: 'DC382D', logo: 'redis' },
    { id: 'sqlite', label: 'SQLite', color: '003B57' },
    { id: 'firebase', label: 'Firebase', color: 'FFCA28', logoColor: 'black' },
    { id: 'supabase', label: 'Supabase', color: '3ECF8E', logoColor: 'white' },
    { id: 'prisma', label: 'Prisma', color: '2D3748' },
    { id: 'elasticsearch', label: 'Elasticsearch', color: '005571' },
    { id: 'neo4j', label: 'Neo4j', color: '008CC1' },
    { id: 'cassandra', label: 'Cassandra', color: '1287B1', logo: 'apachecassandra' },
    { id: 'cockroachdb', label: 'CockroachDB', color: '6933FF' },
  ],
  'Cloud & DevOps': [
    { id: 'aws', label: 'AWS', color: 'FF9900', logo: 'amazonaws', logoColor: 'white' },
    { id: 'gcp', label: 'Google Cloud', color: '4285F4', logo: 'googlecloud', logoColor: 'white' },
    { id: 'azure', label: 'Azure', color: '0078D4', logo: 'microsoftazure' },
    { id: 'docker', label: 'Docker', color: '2496ED' },
    { id: 'kubernetes', label: 'Kubernetes', color: '326CE5' },
    { id: 'linux', label: 'Linux', color: 'FCC624', logoColor: 'black' },
    { id: 'git', label: 'Git', color: 'F05033' },
    { id: 'github-actions', label: 'GitHub Actions', color: '2671E5', logo: 'githubactions' },
    { id: 'terraform', label: 'Terraform', color: '5835CC' },
    { id: 'nginx', label: 'Nginx', color: '009639' },
    { id: 'vercel', label: 'Vercel', color: '000000' },
    { id: 'netlify', label: 'Netlify', color: '00C7B7' },
    { id: 'heroku', label: 'Heroku', color: '430098' },
    { id: 'digitalocean', label: 'DigitalOcean', color: '0080FF' },
    { id: 'cloudflare', label: 'Cloudflare', color: 'F38020', logoColor: 'white' },
  ],
  'Tools': [
    { id: 'vscode', label: 'VS Code', color: '007ACC', logo: 'visualstudiocode' },
    { id: 'figma', label: 'Figma', color: 'F24E1E' },
    { id: 'postman', label: 'Postman', color: 'FF6C37' },
    { id: 'jira', label: 'Jira', color: '0A0FFF' },
    { id: 'notion', label: 'Notion', color: '000000' },
    { id: 'xcode', label: 'Xcode', color: '147EFB' },
    { id: 'androidstudio', label: 'Android Studio', color: '3DDC84', logo: 'androidstudio', logoColor: 'white' },
    { id: 'blender', label: 'Blender', color: 'E87D0D' },
    { id: 'unity', label: 'Unity', color: '000000' },
    { id: 'unrealengine', label: 'Unreal Engine', color: '0E1128', logo: 'unrealengine' },
  ],
  'AI / ML': [
    { id: 'tensorflow', label: 'TensorFlow', color: 'FF6F00' },
    { id: 'pytorch', label: 'PyTorch', color: 'EE4C2C' },
    { id: 'scikit', label: 'scikit-learn', color: 'F7931E', logo: 'scikitlearn', logoColor: 'white' },
    { id: 'pandas', label: 'Pandas', color: '150458' },
    { id: 'numpy', label: 'NumPy', color: '013243' },
    { id: 'opencv', label: 'OpenCV', color: '5C3EE8' },
    { id: 'huggingface', label: 'HuggingFace', color: 'FFD21E', logo: 'huggingface', logoColor: 'black' },
  ],
};

export function getSkillBadgeUrl(skill) {
  const logo = skill.logo || skill.id.replace(/-/g, '').replace(/\./g, 'dot').toLowerCase();
  const logoColor = skill.logoColor || 'white';
  return `https://img.shields.io/badge/${encodeURIComponent(skill.label)}-${skill.color}?style=for-the-badge&logo=${logo}&logoColor=${logoColor}`;
}
